### ISSUE TITLE
适配python3.9申请

### ISSUE THREAD

**Issue by ALEXsun0** [GuGuMur/nonebot-plugin-skland-arksign#22]
> #20 same issue
此错误似乎是由 Python 的类型提示引起的，具体来说是使用了 `|` 符号来表示联合类型。如在这段代码中：`token: str | None = None`
        这里`|`符号用于 Python 3.10 及更高版本的类型提示，表示 token 变量可以是 str 类型或 NoneType。然而，这在 Python 3.9 及以下版本是不支持的，于是报错：`TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
为了后续版本更新跟进，希望能够进行python3.10以下版本的适配。

**Comment by AzideCupric** [comment]
nb本体都快要3.10了

**Comment by AzideCupric** [comment]
不过最新版已经兼容3.9了

**Comment by GuGuMur** [comment]
大概行了（

**Comment by AzideCupric** [comment]
> 大概行了（

大概确乎真的行了 #25
