### ISSUE TITLE
执行签到后出现错误代码10001

### ISSUE THREAD

**Issue by Fui-Reconk** [GuGuMur/nonebot-plugin-skland-arksign#29]
我又来了）
XXXX 签到失败
请检查以下信息：
{'code': 10001, 'message': '当前用户未经授权'}

**Comment by GuGuMur** [comment]
请考虑重新获取token后重绑定，然后检查下是不是顶掉了之前的登录状态

**Comment by AzideCupric** [comment]
是否认真阅读过README并且添加账号时没有忽略任何步骤

**Comment by Fui-Reconk** [comment]
> 请考虑重新获取token后重绑定，然后检查下是不是顶掉了之前的登录状态

好像并不行，依旧是那个样

**Comment by Fui-Reconk** [comment]
> 是否认真阅读过README并且添加账号时没有忽略任何步骤

不出意外的话是一步一步下来的

**Comment by AzideCupric** [comment]
检查一下token怎么发的，有没有以下错误情况
1. 带上了外面那层双引号
2. 发了整个json
3. 游戏uid和token不对应

**Comment by Fui-Reconk** [comment]
> 检查一下token怎么发的，有没有以下错误情况
> 
> 1. 带上了外面那层双引号
> 2. 发了整个json
> 3. 游戏uid和token不对应

UID是数字对吧？（好像发现了问题所在

**Comment by AzideCupric** [comment]
> UID是数字对吧？（好像发现了问题所在
对的 你游戏等级下面那串数字

**Comment by Fui-Reconk** [comment]
坏了我是笨比
