### ISSUE TITLE
跟进新版计算签名的方式

### ISSUE THREAD

**Issue by RF-Tar-Railt** [GuGuMur/nonebot-plugin-skland-arksign#6]
即此处提及的新增的请求头签名：[sign-header](https://gitee.com/FancyCabbage/skyland-auto-sign#sign-header)

不实现此方法则无法进行签到操作

顺便，都用了saa，不考虑一下alc吗 （https://github.com/nonebot/plugin-alconna

**Comment by AzideCupric** [comment]
alc用了喵，在另一个分支里
