### ISSUE TITLE
[Bug]: 鹰角把网页端签到入口关了，脚本签到之后返回405，现在只有APP端能签了好像

### ISSUE THREAD

**Issue by Alcohol233** [GuGuMur/nonebot-plugin-skland-arksign#61]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读插件的 README
- [X] 我的Python版本满足>= 3.10
- [X] 我已经将插件和机器人环境依赖都安装到了推荐/最新版本
- [X] 我确定指令输入并无错误
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。

### 运行环境

Linux

### Nonebot 2 版本

2.1.1

### 重现步骤

立即执行签到操作完成！
签到失败：Client error '405 Not Allowed' for url 'https://zonai.skland.com/api/v1/game/player/binding'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405喵

### 期望的结果是什么？

签到成功

### 实际的结果是什么？

签到失败返回405 not allowed

**Comment by Alcohol233** [comment]
我的机器人用这个插件绑了4个账号进行自动签到，4个账号都在今天出现了405错误，去网页端点森空岛的签到按钮链接变为了下载森空岛APP的apk，所以判断应该是鹰角把网页端的签到给关了。

**Comment by Windsland52** [comment]
> 我的机器人用这个插件绑了4个账号进行自动签到，4个账号都在今天出现了405错误，去网页端点森空岛的签到按钮链接变为了下载森空岛APP的apk，所以判断应该是鹰角把网页端的签到给关了。

https://github.com/Maojuan-lang/SenKongDao试试这个，不过可能得自己写个插件了

**Comment by GuGuMur** [comment]
怎么跟 #60 一样的问题，我自己这几天的都正常啊（

顺便，cc @Windsland52 ，这个插件的原理是模拟客户端登录后的操作，与你提供的库在实现原理上是一样的（本插件也引用了其中的某些部分）

**Comment by Windsland52** [comment]
> 怎么跟 #60 一样的问题，我自己这几天的都正常啊（
> 
> 顺便，cc @Windsland52 ，这个插件的原理是模拟客户端登录后的操作，与你提供的库在实现原理上是一样的（本插件也引用了其中的某些部分）

这个前几天还用着来着，今天也报405了TAT

**Comment by jcjrobert** [comment]
我也喜提405了，换本地跑也不行嘞

**Comment by Alcohol233** [comment]
我重新绑了几次，也刷新过几个token了，看样子多半是用不了了

**Comment by GuGuMur** [comment]
[enpitsuLin/skland-daily-attendance](https://github.com/enpitsuLin/skland-daily-attendance)

~~差点就 自动签到 永久停更 了~~

**Comment by Alcohol233** [comment]
非常好自动签到，使我的服务器旋转

> [enpitsuLin/skland-daily-attendance](https://github.com/enpitsuLin/skland-daily-attendance)
> 
> ~差点就 自动签到 永久停更 了~
